#! /usr/bin/env zsh
echo "Do not execute!" && exit

repo=/tmp/usb/arch-setup
prefix=

# ----------------------------------------
# Save history on disk
# ----------------------------------------
SAVEHIST=10000
HISTSIZE=10000
HISTFILE=/root/.zsh_history
setopt incappendhistory
export EDITOR=vim
export DIFFTOOL=vimdiff

EDIT()
{
    for file in $@; do
        if [[ -f $prefix$file ]]; then
            $DIFFTOOL {$repo,$prefix}$file;
        else
            $EDITOR $prefix$file
        fi
    done
}

lvmdrive=/dev/sda
lvmpart=${lvmdrive}2

# ----------------------------------------
# Generate locale
# ----------------------------------------
passwd
EDIT /etc/locale.gen
locale-gen
EDIT /etc/locale.conf
ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
echo core-problem > /etc/hostname

pacman -S terminus-font
EDIT /etc/vconsole.conf

# ----------------------------------------
# Set hardware clock to UTC
# ----------------------------------------
pacman -S ntp
systemctl enable ntpd.service
hwclock --systohc --utc
ntpd -gq 
hwclock -w

# ----------------------------------------
# Create initial ramdisk
#
# Add the following HOOKS
#  - consolefont    (display custom terminal font early)
#  - keymap         (change to preferred keymap before password prompt)
#  - lvm2           (need lvm before encrypt: LUKS on LVM)
#  - encrypt        (encrypt hook)
#  - filesystems    (encrypt should be loaded before this)
#  - keyboard
#  - shutdown       (for usr)
#  - fsck           (for usr)
#  - usr            (needed since /usr is on separate partition)
#
# Add the following MODULES (make consolefont working)
#  - i915
#  - dm_mod
#  - ext4
# ----------------------------------------
EDIT /etc/mkinitcpio.conf
mkinitcpio -p linux


# ----------------------------------------
# Install grub
#
# Installing os-prober lets you find other OS (dual boot windows). On the
# other hand it may cause ugly error messages during grub-install.
#
# Further warnings may occur within CHROOT environment. You can repeat this
# after rebooting if you do not entirely trust in the result.
#
# Add the following parameter in /etc/default/grub:
# GRUB_CMDLINE_LINUX="cryptdevice=/dev/scsi/root:crypt-root"
# ----------------------------------------
pacman -S grub-bios
pacman -S os-prober
EDIT /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg
grub-install $lvmdrive

