#! /usr/bin/env zsh
echo "Do not execute!" && exit

# ----------------------------------------
# Save history on disk
# ----------------------------------------
SAVEHIST=10000
HISTSIZE=10000
HISTFILE=/root/.zsh_history
setopt incappendhistory
export EDITOR=vim

lvmdrive=/dev/sda
lvmpart=${lvmdrive}2

# ----------------------------------------
# Generate locale
# ----------------------------------------
passwd
$EDITOR /etc/locale.gen
locale-gen
echo "LANG=en_US.UTF-8" > /etc/locale.conf
ln -s /usr/share/zoneinfo/Europe/Berlin /etc/localtime
echo core-problem > /etc/hostname

pacman -S terminus-font
cat <<VCONSOLE > /etc/vconsole.conf
KEYMAP=dvorak-de
ter-216n
FONT_MAP=8859-2_to_uni
VCONSOLE

# ----------------------------------------
# Set hardware clock to UTC
# ----------------------------------------
pacman -S ntp
systemctl enable ntpd.service
hwclock --systohc --utc
ntpd -gq 
hwclock -w

# ----------------------------------------
# Create initial ramdisk
#
# Add the following HOOKS
#  - consolefont    (display custom terminal font early)
#  - keymap         (change to preferred keymap before password prompt)
#  - lvm2           (need lvm before encrypt: LUKS on LVM)
#  - encrypt        (encrypt hook)
#  - filesystems
#  - keyboard
#  - shutdown
#  - fsck
#  - usr            (needed since /usr is on separate partition)
#
# Add the following MODULES (make consolefont working)
#  - i915
#  - dm_mod
#  - ext4
# ----------------------------------------
$EDITOR /etc/mkinitcpio.conf
mkinitcpio -p linux


# ----------------------------------------
# Install grub
#
# Installing os-prober lets you find other OS (dual boot windows). On the
# other hand it may cause ugly error messages during grub-install.
#
# Further warnings may occur within CHROOT environment. You can repeat this
# after rebooting if you do not entirely trust in the result.
#
# Add the following parameter in /etc/default/grub:
# GRUB_CMDLINE_LINUX="cryptdevice=/dev/scsi/root:crypt-root"
# ----------------------------------------
pacman -S grub-bios
pacman -S os-prober
$EDITOR /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg
grub-install $lvmdrive

