#! /usr/bin/env zsh

# ----------------------------------------
# Installer meta config
# ----------------------------------------

# Main install drive+partition
lvmdrive=/dev/sda
lvmpart=${lvmdrive}2

# Your favorite terminal editor
export EDITOR=vim
export DIFFTOOL=vimdiff

# ----------------------------------------
# Edit and compare configuration file with deployed version
#
# Make sure to have $prefix set to the root path of the destination system.
# ----------------------------------------
EDIT()
{
    for file in $@; do
        if [[ -f $prefix$file ]]; then
            $DIFFTOOL {$repo,$prefix}$file;
        else
            $EDITOR $prefix$file
        fi
    done
}

# ----------------------------------------
# Start save history
# ----------------------------------------
HIST()
{
    HISTSIZE=10000
    SAVEHIST=10000
    HISTFILE=$1
    setopt incappendhistory
}

# ----------------------------------------
# Locale (destination system config)
# ----------------------------------------
hostname=core-problem
timezone=Europe/Berlin

